name: my-proj
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.10
  - bioconda::trackhub=0.1.2019.12.24
  - bioconda::pysradb=2.0.1
  - conda-forge::matplotlib-base=3.7.1
  - conda-forge::xdg=6.0.0
  - conda-forge::argcomplete=3.0.5
  - conda-forge::tabulate>=0.9.0
  - conda-forge::conda-ecosystem-user-package-isolation
  - opencv
  - tensorboard
  - pyqt
  - pip:
    - mealpy
    - portray
